CREATE DATABASE bd_barber  /*CREAMOS LA BASE DE DATOS*/
use bd_barber /*LA SELECCIONAMOS PARA USARLA */

--CREAMOS LA TABLA Y LE INGRESAMOS LAS VARIABLES
CREATE TABLE CITA
(
CODIGO VARCHAR(11)PRIMARY KEY,
NOMBRE VARCHAR(100),
DIA VARCHAR(20),
HORA VARCHAR(10),
)

INSERT INTO CITA VALUES('1', 'Deivyth',' Lunes','2:00PM') --LE INGRESAMOS LOS VALORES A LA TABLA EN ORDEN

SELECT * FROM CITA --MOSTRAR TODA LA TABLA

CREATE DATABASE bd_barber  /*CREAMOS LA BASE DE DATOS*/
use bd_barber /*LA SELECCIONAMOS PARA USARLA */

--CREAMOS LA TABLA Y LE INGRESAMOS LAS VARIABLES
CREATE TABLE SERVICIOS
(
CODIGO VARCHAR(11)PRIMARY KEY,
SERVICIO VARCHAR(100),
VALOR VARCHAR(100),
)

INSERT INTO SERVICIOS VALUES('1', 'BARBA',' 500000') --LE INGRESAMOS LOS VALORES A LA TABLA EN ORDEN

SELECT * FROM SERVICIOS --MOSTRAR TODA LA TABLA




CREATE TABLE USUARIOS
(
CODIGO VARCHAR(11)PRIMARY KEY,
USUARIO VARCHAR(100),
CONTRASEÑA VARCHAR(100)
)

INSERT INTO USUARIOS VALUES ('1','admin','123') --LE INGRESAMOS LOS VALORES A LA TABLA EN ORDEN

SELECT * FROM USUARIOS --MOSTRAR TODA LA TABLA

CREATE TABLE EMERGENCIAS
(
CODIGO VARCHAR(11)PRIMARY KEY,
NOMBRE VARCHAR(100),
NUMERO_USUARIO VARCHAR(20),
CORREO_USUARIO VARCHAR(100)
)

INSERT INTO EMERGENCIAS VALUES ('1','INCENDIO','3227425471','DHQUINTERO@GMAIL.COM') --LE INGRESAMOS LOS VALORES A LA TABLA EN ORDEN

SELECT * FROM EMERGENCIAS --MOSTRAR TODA LA TABLA

CREATE TABLE PAGOS
(
CELULAR VARCHAR(12)PRIMARY KEY,
CANTIDAD VARCHAR(100),
MENSAJE VARCHAR(200)
)

INSERT INTO PAGOS VALUES ('3187425471','100.000','Gracias por endeudarte conmigo <3') --LE INGRESAMOS LOS VALORES A LA TABLA EN ORDEN

SELECT * FROM PAGOS--MOSTRAR TODA LA TABLA